export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  SET_CART_UPDATED: "SET_CART_UPDATED",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_ITEM: "ADD_ITEM",
  DELETE_FROM_CART: "DELETE_FROM_CART",
};
